# <font color='darkblue'>Extraindo Dados da Internet e Criando a Carteira "Magic Formula"
### <font color='darkblue'> Documentação Pandas, Fundamentus,  Selenium, Webdriver-manager, 
https://pypi.org/project/pandas/
    
https://www.fundamentus.com.br/index.php
    
https://pypi.org/project/selenium/
      
https://pypi.org/project/webdriver-manager/

### <font color='darkblue'> Objetivo
* Construir um código que vá no site "fundamentus.com" e busque os dados de todos os indicadores da bolsa brasileira, e gere a carteira selecionando as maiores índices ev_ebit e roic.

In [5]:
# Instalar as bibliotecas abaixo:
# !pip install selenium
# !pip install webdriver-manager

In [6]:
# Importar as bibliotecas:
# Pandas é biblioteca open-source e de uso gratuito, que fornece ferramentas para análise e manipulação de dados em Python.
import pandas as pd
# O Selenium é o principal paocote para fazer web scraping
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
# O webdriver é um gerenciados de driver ex. (corregir dados de drive para correção e conecção)
from webdriver_manager.chrome import ChromeDriverManager

### <font color='darkblue'> Entendendo Como Funcionam as Requisições na internet

In [4]:
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
url = 'https://www.fundamentus.com.br/resultado.php'
driver.get(url)

### <font color='darkblue'> Entendendo o Funcionamento do Site "Fundamentus"

#### Vistorie o site Fundamentus, observe sempre sua diagramação, seus dados e sua estrutura.
#### (Front End) é a parte gráfica de um site,  ele é dividido por três estruturas: 
* ##### CSS (Estilização);
* ##### HTML (Posição das coisas); e 
* Obs.: Para ler uma matéia que está travada Ex.(Estadão) efetue o desligamento do JavaScript momentaneamente:
No seu Navegador, click nos três pontinos/configurações/digite (Java Script)/configurações do Site/Embaixo vai aparecer (JavaScript - Os sites podem usar o JavaScript)/ Não permitir que os sites usem JavaScript.
* Depois volte ao normal, senão o site vai ficar desconfigurado..

* ##### Javascript (Movimento).

### <font color='darkblue'> Lendo os Dados do Site Fundamentus

In [22]:
local_tabela = '/html/body/div[1]/div[2]/table'
tabela = driver.find_element("xpath", local_tabela)
html_tabela = tabela.get_attribute('outerHTML')
tabela = pd.read_html(str(html_tabela), thousands = '.', decimal = ',')[0]
tabela

,Papel,Cotação,P/L,P/VP,PSR,Div.Yield,P/Ativo,P/Cap.Giro,P/EBIT,P/Ativ Circ.Liq,...,EV/EBITDA,Mrg Ebit,Mrg. Líq.,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a
0,CSTB4,147.69,0.00,0.00,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"40,85%","28,98%",2.60,"22,40%","20,11%",0.0,8.420670e+09,0.14,"31,91%"
1,MNSA4,0.47,0.00,0.00,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"-208,15%","-362,66%",3.63,"-13,50%","145,70%",0.0,-9.105000e+06,-6.52,"-41,11%"
2,PORP4,2.40,0.00,0.00,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","-2,08%",0.0,2.239900e+07,0.00,"13,66%"
3,POPR4,10.17,0.00,0.00,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"8,66%","5,65%",1.08,"15,25%","19,93%",0.0,5.458030e+08,0.82,"30,93%"
4,IVTT3,0.00,0.00,0.00,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","-0,40%",0.0,1.083050e+09,0.00,"20,67%"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
982,PRBC4,14.54,502.29,40.26,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","8,02%",0.0,1.176410e+09,0.00,"-6,01%"
983,UBBR4,7.49,610.27,1.99,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","0,33%",0.0,1.031720e+10,0.00,"10,58%"
984,UBBR11,14.75,1201.81,3.91,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","0,33%",0.0,1.031720e+10,0.00,"10,58%"
985,UBBR3,18.00,1466.61,4.77,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","0,33%",0.0,1.031720e+10,0.00,"10,58%"
986,SQIA3,26.75,2682.38,3.68,3.583,"0,21%",1.466,26.44,42.26,-3.64,...,16.14,"8,48%","0,45%",1.44,"4,04%","0,14%",25244300.0,6.397490e+08,0.67,"46,25%"

### <font color='darkblue'> Construindo a Tabela Final

In [23]:
tabela = tabela.set_index("Papel")
tabela = tabela[['Cotação', 'EV/EBIT', 'ROIC', 'Liq.2meses']]
tabela

        Cotação  EV/EBIT     ROIC  Liq.2meses
Papel
CSTB4    147.69     0.00   22,40%         0.0
MNSA4      0.47     0.00  -13,50%         0.0
PORP4      2.40     0.00    0,00%         0.0
POPR4     10.17     0.00   15,25%         0.0
IVTT3      0.00     0.00    0,00%         0.0
...         ...      ...      ...         ...
PRBC4     14.54     0.00    0,00%         0.0
UBBR4      7.49     0.00    0,00%         0.0
UBBR11    14.75     0.00    0,00%         0.0
UBBR3     18.00     0.00    0,00%         0.0
SQIA3     26.75    46.06    4,04%  25244300.0

[987 rows x 4 columns]

### <font color='darkblue'> Transformando o Texto em Números

In [24]:
#tabela['EV/EBIT'] * tabela['ROIC']
tabela.info()

<class 'pandas.core.frame.DataFrame'>
Index: 987 entries, CSTB4 to SQIA3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Cotação     987 non-null    float64
 1   EV/EBIT     987 non-null    float64
 2   ROIC        987 non-null    object
 3   Liq.2meses  987 non-null    float64
dtypes: float64(3), object(1)
memory usage: 38.6+ KB

### <font color='darkblue'> Tratamento de Informação

In [25]:
# Vamos transformar o ROIC "object" em número
# Vamos usar a função st,replace para fazer essa conversão de toda a tabela ou coluna
# Nesse caso vamos transformar apena a coluna ROIC em número, observar que o Brasil trabalha com (ponto e virgula)

In [26]:
tabela['ROIC'] = tabela['ROIC'].str.replace('%', '')
tabela['ROIC'] = tabela['ROIC'].str.replace('.', '', regex=True)
tabela['ROIC'] = tabela['ROIC'].str.replace(',', '.', regex=True)  
tabela['ROIC'] = tabela['ROIC'].astype(float)
tabela

        Cotação  EV/EBIT   ROIC  Liq.2meses
Papel
CSTB4    147.69     0.00  22.40         0.0
MNSA4      0.47     0.00 -13.50         0.0
PORP4      2.40     0.00   0.00         0.0
POPR4     10.17     0.00  15.25         0.0
IVTT3      0.00     0.00   0.00         0.0
...         ...      ...    ...         ...
PRBC4     14.54     0.00   0.00         0.0
UBBR4      7.49     0.00   0.00         0.0
UBBR11    14.75     0.00   0.00         0.0
UBBR3     18.00     0.00   0.00         0.0
SQIA3     26.75    46.06   4.04  25244300.0

[987 rows x 4 columns]

### <font color='darkblue'> Fazendo os Filtros e Criando os Rankings

Efetuamos o filtro com a coluna "Liquizes" maior que R$ 1.000.000,00

In [27]:
tabela = tabela[tabela['Liq.2meses'] > 1000000]
tabela

       Cotação  EV/EBIT   ROIC   Liq.2meses
Papel
QUAL3     3.84     5.17  13.95   19978500.0
MEGA3    10.59    25.04   3.66    8347000.0
LWSA3     6.73    44.79   2.03   51449900.0
CBAV3     4.24    86.75   0.53   35512900.0
MYPK3    14.47     9.05   6.73   21522400.0
...        ...      ...    ...          ...
YDUQ3    22.45    14.96   8.99  116203000.0
CRFB3    11.85     9.00   6.66  120957000.0
CEAB3     6.23     7.74   5.28   26577600.0
PTBL3     6.79    11.09   7.36   10946900.0
SQIA3    26.75    46.06   4.04   25244300.0

[244 rows x 4 columns]

In [28]:
tabela = tabela[tabela['EV/EBIT'] > 0]
tabela = tabela[tabela['ROIC'] > 0]
tabela

       Cotação  EV/EBIT   ROIC   Liq.2meses
Papel
QUAL3     3.84     5.17  13.95   19978500.0
MEGA3    10.59    25.04   3.66    8347000.0
LWSA3     6.73    44.79   2.03   51449900.0
CBAV3     4.24    86.75   0.53   35512900.0
MYPK3    14.47     9.05   6.73   21522400.0
...        ...      ...    ...          ...
YDUQ3    22.45    14.96   8.99  116203000.0
CRFB3    11.85     9.00   6.66  120957000.0
CEAB3     6.23     7.74   5.28   26577600.0
PTBL3     6.79    11.09   7.36   10946900.0
SQIA3    26.75    46.06   4.04   25244300.0

[197 rows x 4 columns]

### <font color='darkblue'> Observação Importante

Nós queremos o índice EV/EBIT o menor possível, e o ROIC maior possível
Ou seja, queremos a empresa mais barata (EV/BIT), com maior qualidade (ROIC) ao mesmo tempo

Seque a carteira encolhida das 10 melhores empresas para compra nessa data:

In [29]:
tabela['ranking_ev_ebit'] = tabela['EV/EBIT'].rank(ascending = True)
tabela['ranking_roic'] = tabela['ROIC'].rank(ascending = False)
tabela['ranking_total'] = tabela['ranking_ev_ebit'] + tabela['ranking_roic']

tabela = tabela.sort_values('ranking_total')
tabela.head(10)

,Cotação,EV/EBIT,ROIC,Liq.2meses,ranking_ev_ebit,ranking_roic,ranking_total
Papel,,,,,,,
PSSA3,27.52,0.26,60.76,5.775590e+07,1.0,1.0,2.0
PETR4,31.52,2.41,28.95,1.602730e+09,4.0,10.5,14.5
PETR3,34.49,2.56,28.95,4.355100e+08,5.0,10.5,15.5
UNIP3,71.77,4.51,38.68,1.011170e+06,14.5,3.5,18.0
WIZC3,5.91,2.20,24.18,4.456770e+06,3.0,17.0,20.0
KEPL3,10.63,4.71,43.61,1.530740e+07,20.0,2.0,22.0
FESA4,43.08,4.06,25.57,9.651050e+06,8.0,15.0,23.0
UNIP6,76.40,4.81,38.68,1.710480e+07,21.0,3.5,24.5
CMIN3,4.06,4.57,28.49,2.922810e+07,18.0,12.0,30.0
VLID3,16.85,4.14,20.64,6.210320e+06,10.0,23.0,33.0

###### <font color='Red'> Projeto (03/11/2023): Extraindo Dados da Internet e Criando a Carteira "Magic Formula" - William E. Santos.